### ISSUE TITLE
Question: how do you make it work in mac os 11?

### ISSUE THREAD

**Issue by inviolablegenesis** [a1exsh/google-java-format-git-pre-commit-hook#15]
Sorry if this is such a dumb question. 
I'm new to git hooks so I'm not sure if I'm doing it right. 

Do I need to download something? 

I tried to put the `pre-commit` file in .git/hooks directory but when I ran `git commit -am "test"` (sample only), it will always output 
`fatal: cannot run .git/hooks/pre-commit: No such file or directory`

I even tried to change the permissions of the file.
May I know how to make it work?

**Comment by a1exsh** [comment]
@inviolablegenesis sorry, I've just noticed your question ;)  It doesn't seem to be specific to the hook, but rather how you set it up on your system.  I'd recommend trying to make it work with some "hello world" hook first, e.g. the `.git/hook/pre-commit.sample` provided by git itself.
