### ISSUE TITLE
Proposal: Introduce verbose flag

### ISSUE THREAD

**Issue by spotlesscoder** [a1exsh/google-java-format-git-pre-commit-hook#19]
I want to add a verbose flag to the script that runs all executed commands support verbose flags as well (e.g. gpg --verify etc.) with a verbose flag to analyze failures.

Also, when that flag is set, I want additional `echo` texts to be printed to the command line to get a better tracing of what the script is currently doing.

**Comment by a1exsh** [comment]
@CodingSpiderFox what if you just run it via shell with `-x`, like this: https://github.com/a1exsh/google-java-format-git-pre-commit-hook/blob/master/.github/workflows/check.yml#L10 ?

**Comment by spotlesscoder** [comment]
Yes, that should work for now, thank you :)
