### ISSUE TITLE
Move from 1.15.0 to the last release 

### ISSUE THREAD

**Issue by fabiobsantosprogrow** [a1exsh/google-java-format-git-pre-commit-hook#20]
When I try to update the release version I get this error:
![image](https://github.com/user-attachments/assets/c0b5d1a6-f656-410f-be3f-509d850c7b31)
Could you please tell the steps to update the pgp signature?

**Comment by a1exsh** [comment]
For the current latest version (1.23.0), the signature should be obtained from this location: https://repo1.maven.org/maven2/com/google/googlejavaformat/google-java-format/1.23.0/google-java-format-1.23.0-all-deps.jar.asc
