### ISSUE TITLE
the script requires commit under root folder

### ISSUE THREAD

**Issue by tracyhenry** [a1exsh/google-java-format-git-pre-commit-hook#3]
the workaround I got is to prepend any reference to the jar with `$GIT_DIR/`

**Comment by a1exsh** [comment]
I cannot reproduce this on git version 2.17.1.  How does it fail specifically in your case?

**Comment by tracyhenry** [comment]
sorry, doesn't seem like it's a root/child folder problem. But I got this error when I try to commit for the first time:
```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   625    0   625    0     0   3102      0 --:--:-- --:--:-- --:--:--  3109
100 5596k  100 5596k    0     0  7364k      0 --:--:-- --:--:-- --:--:-- 10.7M
curl: Saved to filename 'google-java-format-1.6-all-deps.jar'
shasum: .cache/google-java-format-1.6-all-deps.jar: 
.cache/google-java-format-1.6-all-deps.jar: FAILED open or read
shasum: WARNING: 1 listed file could not be read
```

And this error went away if I commit again. I'm on macOS

When I prepend any reference to the jar with `$GIT_DIR`, I don't get this error on first try.

**Comment by a1exsh** [comment]
Hm, interesting.  No idea why it would work on the 2nd try...

Now that I think about it, maybe it would make more sense to have the cache dir in user's `$HOME`, since one may have many git repos where this is used and then the jar is downloaded and stored multiple times.

**Comment by a1exsh** [comment]
@tracyhenry I've pushed a change that moves the cached jar to `$HOME`.  Not likely this will fix your issue, but could you give it a try just in case? ;)

**Comment by a1exsh** [comment]
Alright, I've figured out a better way to check the signature.  The one that I had wasn't *that* reliable after all: I think I've just generated it myself not knowing that signatures are provided on maven (and that all-deps jar is also pushed there).

With the latest commit (9570bce13f19ffbf75ca2f9a5a8cb80ff172849c) PGP signature from maven is used to verify integrity of the downloaded artifact.

**Comment by tracyhenry** [comment]
Hey I got the following output:
```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   625    0   625    0     0   1032      0 --:--:-- --:--:-- --:--:--  1031
100 5596k  100 5596k    0     0  1473k      0  0:00:03  0:00:03 --:--:-- 2190k
curl: Saved to filename 'google-java-format-1.6-all-deps.jar'
Not a git repository
To compare two paths outside a working tree:
usage: git diff [--no-index] <path> <path>
No Java files changes found.
[master 5314331] haha
 1 file changed, 1 insertion(+), 1 deletion(-)
```

Seems like the scripts were working under the cache directory, not the git repo.

**Comment by a1exsh** [comment]
Just to confirm, what is the output of `git --version` on your system?

**Comment by tracyhenry** [comment]
git version 2.10.1

**Comment by a1exsh** [comment]
I've figured it out now, sorry for confusion.  Pushing the fix now.

**Comment by a1exsh** [comment]
@tracyhenry please use the latest master.  Indeed it was failing the first time after cleaning up the local state, no idea why didn't I see it.  Thanks for reporting! :)
