### ISSUE TITLE
Update to google-java-format 1.9

### ISSUE THREAD

**Issue by mustaphazorgati** [a1exsh/google-java-format-git-pre-commit-hook#9]
Hey there!

I just saw this pre-commit-hook and think it is very cool!
Are you still maintaining this?
If yes: could you please update google-java-format from 1.7 to 1.9?

**Comment by a1exsh** [comment]
@mustaphazorgati sure, thanks for asking :)

**Comment by mustaphazorgati** [comment]
thanks @a1exsh!
